### ISSUE TITLE
Saigon

### ISSUE THREAD

**Issue by dominhhai** [nodeschool/hcmc-vietnam#2]
I don't know why you added saigon after hcmc.
For Vietnamese, we prefer Ho Chi Minh than Saigon.

**Comment by dominhhai** [comment]
Sorry and thank you!

**Comment by okaiji** [comment]
No worry! Still learning much with you on this matter =)

**Comment by dominhhai** [comment]
I want to cooperate with your chapter in order to make strong Vietnam community :100: 

How about use the same chat place?
https://gitter.im/nodeschool/vietnam-chapter
